package global

import (
	"github.com/astaxie/beego/session"
)

// session 管理
var GlobalSessions *session.Manager

// NO ERROR

const (
	NO_ERROR = 0
)

// LOGIN CODE
const (
	LOGIN_SUCCESS = 20000 + iota
	LOGIN_ACCOUNT_OR_PASSWORD_WRONG
	LOGIN_ACCOUNT_OR_PPASSWORD_ILLEGAL
	LOGIN_ACCOUNT_OR_PPASSWORD_OUT_OF_RANGE
	LOGIN_FAILED
)

// LOGIN STRING
const (
	LOGIN_STRING_SUCCESS                           = "登录成功"
	LOGIN_STRING_ACCOUNT_OR_PASSWORD_WRONG         = "账号或密码错误"
	LOGIN_STRING_ACCOUNT_OR_PPASSWORD_ILLEGAL      = "账号或密码非法"
	LOGIN_STRING_ACCOUNT_OR_PPASSWORD_OUT_OF_RANGE = "账号或密码长度超限"
	LOGIN_STRING_FAILED                            = "登录失败"
)

// HTTP CODE
const (
	HTTP_STATUS_OK           = 200
	HTTP_STATUS_NOT_FOUND    = 404
	HTTP_STATUS_REDIRICT     = 302
	HTTP_STATUS_SERVER_WRONG = 500
)

// ERROR CODE
const (
	ERROR_DATABASE_INIT_ERROR = iota + 10000
	ERROR_DATABASE_CANT_INSERT
	ERROR_DATABASE_CANT_UPDATE
	ERROR_DATEBASE_DATA_NOT_FOUND
	ERROR_DATABASE_SAME_KEY
	ERROR_DATABASE_DELETE_FAILDE
)

// ERROR STRING
const (
	ERROR_STRING_DATABASE_INIT_ERROR     = "数据库初始化失败"
	ERROR_STRING_DATABASE_CANT_INSERT    = "数据库插入失败"
	ERROR_STRING_DATABASE_CANT_UPDATE    = "数据库更新失败"
	ERROR_STRING_DATEBASE_DATA_NOT_FOUND = "数据未查询到"
	ERROR_STRING_DATABASE_SAME_KEY       = "数据库插入时有相同主键"
	ERROR_STRING_DATABASE_DELETE_FAILDE  = "数据库删除失败"
)

// SESSION CODE
const (
	ERROR_SESSION_NOT_FOUNT = 30000 + iota
	ERROR_PRAM_ILLEGAL
)

// SESSION STRING
const (
	ERROR_STRING_SESSION_NOT_FOUNT = "session不存在"
	ERROR_STRING_PRAM_ILLEGAL      = "参数非法"
)
